version: 0.0
os: linux
files:
- source: /
  destination: /home/ec2-user/app
hooks:
  AfterInstall:
  - location: scripts/install_python3
    timeout: 300
    runas: root
  - location: scripts/codestar_remote_access
    timeout: 300
    runas: root
  - location: scripts/install_node
    timeout: 300
    runas: root
  - location: scripts/install_httpd
    timeout: 300
    runas: root
  ApplicationStart:
  - location: scripts/start_server
    timeout: 300
    runas: root
    